import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Booking.module.scss'
import Register from '@/components/Register/Register'
import Nav from '@/components/Navbar/Navbar'
import { useState } from 'react'
import Sidepanel from '@/components/BookingPage/SidePanel/sidepanel'
import Viewhotel from '@/components/BookingPage/ViewHotel/viewhotel'
import MobileSearchScreen from '@/components/BookingPage/MobileSearchScreen/MobileSearchScreen'

const inter = Inter({ subsets: ['latin'] })

export default function Booking(){
    const [ isActive, setIsActive ] = useState(false);
    const toggleActiveState = () => setIsActive(!isActive);
    const [selectedHotel, setSelectedHotel] = useState(null);
    const [presetHotel, setPresetHotel] = useState(null)
    
    return (
        <>
            <Head>
              <title>Savvy</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileSearchScreen toggleShow={true}/>
            <main className={styles.main}>
                <Register 
                  isActive={isActive} 
                  toggleActiveState={toggleActiveState}
                />
                <Nav 
                  isActive={isActive} 
                  toggleActiveState={toggleActiveState} 
                />
                <section className='d-flex w-100'>
                    <Sidepanel 
                      selectedHotel={setSelectedHotel} 
                      setPresetHotel={setPresetHotel}
                    />
                    <div className={styles.viewhotel_div}>
                        <Viewhotel 
                          selectedHotel={selectedHotel}
                          preset={presetHotel} 
                        />
                    </div>
                </section>
            </main>
        </>
    )
}