import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Nav from '@/components/Nav/Nav'
import Register from '@/components/Register/Register'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [ isActive, setIsActive ] = useState(false);
  const toggleActiveState = () => setIsActive(!isActive);

  return (
    <>
      <Head>
        <title>Savvy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Register isActive={isActive} toggleActiveState={toggleActiveState}/>
      <Nav isActive={isActive} toggleActiveState={toggleActiveState} />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.landing}>
              <div className={styles.landingNav}>
                <button className={styles.button}>
                  <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="rgba(255,255,255,.6)" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                  </svg>
                </button>
                <button className={styles.button}>
                  <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="rgba(255,255,255,.6)" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                    <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                  </svg>
                </button>
                <input className={styles.input} type='text' />
              </div>
              <div className={styles.landingDiv}>
                <i>
                  <h1 className={styles.landingText}>Savvy Relaxation, Satisfies The Need</h1>
                </i>
                <i>
                  <p className={styles.landingDesc}>Take a Quick Getaway with Ease through Savvy Online Booking Service</p>
                </i>
              </div>
        </div>
      </main>
    </>
  )
}
