import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import Nav from '@/components/Nav/Nav'
import Register from '@/components/Register/Register'
import { useState } from 'react'
import LandingSection from '@/components/Landing/landing'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [ isActive, setIsActive ] = useState(false);
  const toggleActiveState = () => setIsActive(!isActive);
  const [isHovered, setIsHovered] = useState(false);

  const handleMouseEnter = () => {
    setIsHovered(true);
  };

  const handleMouseLeave = () => {
    setIsHovered(false);
  };

  const containerImgs = [
    {id:1, src: '/images/resort.webp', alt: 'RESORTS'},
    {id:2, src: '/images/apartment.webp', alt: 'APARTMENTS'},
    {id:3, src: '/images/hotel.webp', alt: 'HOTELS'}
  ]
  return (
    <>
      <Head>
        <title>Savvy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Register isActive={isActive} toggleActiveState={toggleActiveState}/>
      <Nav isActive={isActive} toggleActiveState={toggleActiveState} />
      <main className={`${styles.main} ${inter.className}`}>
        <LandingSection/>
        <div className={styles.container}>
          <div className={styles.textSection}>
            <h3 className={styles.containerSubtitle}>Seamless Reservations at Your Fingertips</h3>
            <p className={styles.containerDesc}>No more time-consuming phone calls, now you have the power to book services at your convenience.</p>
          </div>
          <div className={`mt-5 ${styles.containerImgs}`}>
                {containerImgs.map((img) => {
                      return (
                        <div className={styles.img} style={{backgroundImage:`url(${img.src})`}}>
                          
                        </div>
                      )
                  }
                )}
          </div>
        </div>
      </main>
    </>
  )
}
